// deploy_ckb.mjs - deploy the NEW CKB scripts for the bridged token to Pudge testnet, and print the exact
// values to paste into src/config.ts. KEY SAFETY: the deployer private key is read from the env at runtime
// (CKB_DEPLOYER_KEY) and is NEVER written anywhere. Run this on YOUR machine, not in a shared/ephemeral box.
//
//   CKB_DEPLOYER_KEY=0x<privkey> BOUND_TYPE_HASH=0x<deployed BoundAsset type-script hash> \
//     node scripts/deploy_ckb.mjs
//
// What it does (two type-id'd cells, so each has a stable, unique code/type hash):
//   1. deploys the leap-mint guard binary as a code cell;
//   2. creates the admin policy cell (caps/pause), initially OPEN (not paused, no caps), admin = deployer;
//   3. derives the guard lock (xUDT owner) and prints the full config block + the cell-deps a leap tx needs.
// The xUDT + Unique + BoundAsset are already on Pudge; this only adds the two new pieces.
import { ccc } from "@ckb-ccc/core";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const GUARD_BIN = resolve(__dir, "../../guard/ckb_script/target/riscv64imac-unknown-none-elf/release/leap_mint_guard");

// well-known constants on Pudge testnet
const TYPE_ID_CODE_HASH = "0x00000000000000000000000000000000000000000000000000545950455f4944";
const XUDT_CODE_HASH = "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"; // CCC KnownScript.XUdt (testnet)

function need(name) {
  const v = process.env[name];
  if (!v) {
    console.error(`\nMissing env ${name}.\nUsage:\n  CKB_DEPLOYER_KEY=0x... BOUND_TYPE_HASH=0x... node scripts/deploy_ckb.mjs\n`);
    process.exit(1);
  }
  return v;
}

/** Deploy one cell carrying `data`, secured by a fresh type-id type script (a unique singleton). Returns the
 *  out-point, the type-id type script, and its hash. */
async function deployTypeIdCell(signer, data, lock) {
  const typePlaceholder = ccc.Script.from({ codeHash: TYPE_ID_CODE_HASH, hashType: "type", args: `0x${"00".repeat(32)}` });
  const tx = ccc.Transaction.from({ outputs: [{ lock, type: typePlaceholder }], outputsData: [ccc.hexFrom(data)] });
  // fund: output capacity = the cell's occupied minimum (structure + data)
  tx.outputs[0].capacity = (BigInt(tx.outputs[0].occupiedSize) + BigInt(ccc.bytesFrom(data).length)) * 100_000_000n;
  await tx.completeInputsByCapacity(signer);
  // now the first input is known -> set the real type-id (same 32-byte length, capacity unchanged)
  const typeId = ccc.hashTypeId(tx.inputs[0], 0);
  tx.outputs[0].type = ccc.Script.from({ codeHash: TYPE_ID_CODE_HASH, hashType: "type", args: typeId });
  await tx.completeFeeBy(signer);
  const txHash = await signer.sendTransaction(tx);
  const typeScript = ccc.Script.from({ codeHash: TYPE_ID_CODE_HASH, hashType: "type", args: typeId });
  return { txHash, outPoint: { txHash, index: 0 }, typeScript, typeHash: typeScript.hash() };
}

async function main() {
  const key = need("CKB_DEPLOYER_KEY");
  const boundTypeHash = need("BOUND_TYPE_HASH");
  const client = new ccc.ClientPublicTestnet();
  const signer = new ccc.SignerCkbPrivateKey(client, key);
  const lock = (await signer.getRecommendedAddressObj()).script;
  console.error(`deployer: ${await signer.getRecommendedAddress()}`);

  // 1) the policy cell first (its type hash feeds the guard args). Open policy: flags=0, min=0, max=0.
  const policyData = new Uint8Array(33); // [flags=0][min=0(16)][max=0(16)]
  console.error("deploying policy cell…");
  const policy = await deployTypeIdCell(signer, policyData, lock);
  console.error(`  policy tx ${policy.txHash}`);

  // 2) the guard code cell.
  const guardBin = readFileSync(GUARD_BIN);
  console.error("deploying leap-mint guard code cell…");
  const guard = await deployTypeIdCell(signer, guardBin, lock);
  console.error(`  guard tx ${guard.txHash}`);

  // 3) derive the guard lock (= the xUDT owner). guard args = xudt_code_hash ‖ bound_type_hash ‖ policy_type_hash
  const guardArgs = ccc.hexFrom(ccc.bytesConcat(
    ccc.bytesFrom(XUDT_CODE_HASH),
    ccc.bytesFrom(boundTypeHash),
    ccc.bytesFrom(policy.typeHash),
  ));
  const guardLock = ccc.Script.from({ codeHash: guard.typeHash, hashType: "type", args: guardArgs });
  const owner = guardLock.hash(); // the xUDT owner-mode args

  // ---- the config block to paste into src/config.ts ----
  console.log(`
// ===== generated by deploy_ckb.mjs (Pudge) - paste into src/config.ts =====
export const CKB = {
  network: "testnet",
  xudtCodeHash: "${XUDT_CODE_HASH}",
  xudtHashType: "type",
  // xUDT OWNER = the leap-mint guard lock hash (the guard runs as the owner lock)
  bridgeLockHash: "${owner}",
  policyType: {
    codeHash: "${policy.typeScript.codeHash}",
    hashType: "type",
    args: "${policy.typeScript.args}",
  },
  minTokenCellCkb: 145,
};

// cell-deps a leap tx must include (besides the system xUDT/Unique dep group + the BoundAsset dep):
//   guard code cell : ${guard.outPoint.txHash}:${guard.outPoint.index}  (dep_type: code)
//   policy cell     : ${policy.outPoint.txHash}:${policy.outPoint.index}  (dep_type: code)  [reference]
//   guard lock hash : ${owner}
//   guard code hash : ${guard.typeHash}
//   bound type hash : ${boundTypeHash}
// ===========================================================================
`);
}

main().catch((e) => { console.error(e); process.exit(1); });
